### ISSUE TITLE
Thanks, and Carpentry Question?

### ISSUE THREAD

**Issue by gkenyon** [twstokes/labs#12]
Hello! I stumbled across your project and just wanted to reach out and say thank you! I am planning to use the button for a 4-year-old's Zoom class. I really couldn't believe there wasn't a software or other hackable solution for muting on iOS with a single key press...

Anyways, everything makes sense to me, going to order the Adafruit Feather BLE board, but had to ask if you built the box yourself? I don't have any carpentry skills so was going to 3D print a case but if there was a more elegant solution that you used I wanted to reach out and ask. Thanks again!

**Comment by twstokes** [comment]
Howdy! Glad you found the project useful! Same here on the carpentry skills - the wooden box came from craft store like Michaels or Hobby Lobby, and all I did was drill the hole for the button. If I had a 3D printer I probably would've gone that route for a better form factor.
